class PyRectangle:
    def __init__(self, a: int, b: int, c: int, d: int) -> None: ...
    def get_area(self) -> int: ...
    def get_size(self) -> tuple[int, int]: ...
    def move(self, dx: int, dy: int) -> None: ...
    @property
    def x0(self) -> int: ...
    @x0.setter
    def x0(self, x0: int) -> None: ...
    @property
    def x1(self) -> int: ...
    @x1.setter
    def x1(self, x1: int) -> None: ...
    @property
    def y0(self) -> int: ...
    @y0.setter
    def y0(self, y0: int) -> None: ...
    @property
    def y1(self) -> int: ...
    @y1.setter
    def y1(self, y1: int) -> None: ...
